// ui/src/repositories/git-branch/GitBranch.tsx
import { Component } from 'solid-js';
import styles from './GitBranch.module.css';
import { PipelineStatus } from '../../types';
import PipelineStatusIcon from '../pipeline-status-icon/PipelineStatusIcon';
const GitBranch: Component<{
  name: string;
  pipelineStatus: PipelineStatus;
  pipelineUrl: string | undefined;
}> = (props) => {
  return (
    <div class={styles.branch}>
      <i class="fa-solid fa-code-branch" title="Branch" />
      {props.pipelineUrl ? (
        <a href={props.pipelineUrl} target="_blank">
          <PipelineStatusIcon pipelineStatus={props.pipelineStatus} />
        </a>
      ) : (
        <PipelineStatusIcon pipelineStatus={props.pipelineStatus} />
      )}
      <span class={styles.branchName}>{props.name}</span>
    </div>
  );
};
export default GitBranch;

// ui/src/lib/GitBranch.svelte
<script lang="ts">
  import type { PipelineStatus } from "../types";
  import PipelineStatusIcon from "./PipelineStatusIcon.svelte";

  export let name: string;
  export let pipelineStatus: PipelineStatus;
  export let pipelineUrl: string | undefined;
</script>

<div class="branch">
  <i class="fa-solid fa-code-branch" title="Branch" />
  {#if pipelineUrl}
    <a href={pipelineUrl} target="_blank">
      <PipelineStatusIcon {pipelineStatus} />
    </a>
  {:else}
    <PipelineStatusIcon {pipelineStatus} />
  {/if}
  <span class="branch-name">{name}</span>
</div>

<style>
  .branch {
    display: flex;
    align-items: center;
    padding: 0.25rem 0;
  }

  .branch-name {
    margin-left: 1rem;
  }

  .branch > :global(*:not(:first-child)) {
    margin-left: 0.5rem;
  }
</style>
